// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaNaKMcM4ULcGrntJhrgANQnrnN6aNPQE',
    appId: '1:64989419750:web:1f19e75c30d26ccd694327',
    messagingSenderId: '64989419750',
    projectId: 'portfolio-98fd7',
    authDomain: 'portfolio-98fd7.firebaseapp.com',
    storageBucket: 'portfolio-98fd7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3p27J46euBaiXUUXXnzlVjNFq9Lo8up8',
    appId: '1:64989419750:android:af0176537331c92a694327',
    messagingSenderId: '64989419750',
    projectId: 'portfolio-98fd7',
    storageBucket: 'portfolio-98fd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv0rXH6FJX_ZWR_FH0qI07JlF1dLHCcxI',
    appId: '1:64989419750:ios:38f31f5625969f79694327',
    messagingSenderId: '64989419750',
    projectId: 'portfolio-98fd7',
    storageBucket: 'portfolio-98fd7.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );
}
